name = "SimplePosets"
uuid = "b2aef97b-4721-5af9-b440-0bad754dc5ba"
version = "0.1.7"

[deps]
FlexLinearAlgebra = "b67e1e5a-d13e-5892-ad81-fb75f5903773"
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"
SimpleGraphs = "55797a34-41de-5266-9ec1-32ac4eb504d3"
SimplePartitions = "ec83eff0-a5b5-5643-ae32-5cbf6eedec9d"

[compat]
julia = "1"
FlexLinearAlgebra = "0.0.2, 0.0.3, 0.1.0"
Primes = "0.4, 0.5"
SimpleGraphs = "0.8"
SimplePartitions = "0.0.1, 0.1, 0.2, 0.3"

[extras]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["LinearAlgebra", "Test"]
